/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { BuyModelUpdate } from '../model/buyModelUpdate';
import { Responses } from '../model/responses';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class BuyModelService {

    protected basePath = 'https://us-central1-gomdon-74d1a.cloudfunctions.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Xem toàn bộ buyModel của một đơn mua
     * @param gomdon_buy_id gomdon_buy_id là id document của đơn mua
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getModelOfBuy(gomdon_buy_id: string, observe?: 'body', reportProgress?: boolean): Observable<Responses>;
    public getModelOfBuy(gomdon_buy_id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Responses>>;
    public getModelOfBuy(gomdon_buy_id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Responses>>;
    public getModelOfBuy(gomdon_buy_id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (gomdon_buy_id === null || gomdon_buy_id === undefined) {
            throw new Error('Required parameter gomdon_buy_id was null or undefined when calling getModelOfBuy.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Responses>(`${this.configuration.basePath}/buy-model/gomdon-buy-id/${encodeURIComponent(String(gomdon_buy_id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Cập nhật thông tin phân loại của đơn mua
     * Cập nhật thông tin phân loại của đơn mua
     * @param BuyModelUpdate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateBuyModel(BuyModelUpdate: BuyModelUpdate, observe?: 'body', reportProgress?: boolean): Observable<Responses>;
    public updateBuyModel(BuyModelUpdate: BuyModelUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Responses>>;
    public updateBuyModel(BuyModelUpdate: BuyModelUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Responses>>;
    public updateBuyModel(BuyModelUpdate: BuyModelUpdate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (BuyModelUpdate === null || BuyModelUpdate === undefined) {
            throw new Error('Required parameter BuyModelUpdate was null or undefined when calling updateBuyModel.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Responses>(`${this.configuration.basePath}/buy-model`,
            BuyModelUpdate,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
